- name: Cron job
  hosts: all
  tasks:
    - name: work
      cron:
        minute: "30"
        hour:  "23"
        day: "*"
        month: "*"
        weekday: "3"
        user: root
        job: "/tmp/file.sh"