- name: Cron job
  hosts: all
  tasks:
    - name: work
      cron:
        name: cronjob
        minute: "35"
        hour:  "23"
        day: "*"
        month: "*"
        weekday: "2"
        user: root
        job: "/tmp/file.sh"