- name: Corn job
  hosts: all
  tasks:
    - name: work
      corn:
        minute: "0"
        hour:  "10"
        day: "*"
        month: "*"
        weekday: "4"
        user: root
        job: "/tmp/file.sh"