- name: Corn job
  hosts: all
  tasks:
    - name: work
      corn:
        minute: "28"
        hour:  "23"
        day: "*"
        month: "*"
        weekday: "3"
        user: root
        job: "/tmp/file.sh"